trigger: none
pr: none
pool:
  vmImage: 'vs2017-win2016'
resources:
  repositories:
  - repository: Git-POC
    type: github
    endpoint: ajaydell
    name: ajaydell/Git-POC
    ref: master

steps:
- checkout: Git-POC
- template: resource.azure.yml
  
