resources:
  repositories:
  - repository: ADFtest
    type: github
    endpoint: MyGitHubServiceConnection
    name: ajaydell/ADFtest
    ref: main

steps:
- checkout: ADFtest
trigger: none
pr: none
pool:
  vmImage: 'vs2017-win2016'
  
